development:
  adapter:  postgresql
  host:     civicbook.cshwoppdfhns.us-east-1.rds.amazonaws.com
  encoding: unicode
  database: civicbook
  pool:     5
  username: civicbook
  password: civicbook
  template: template0
  port: 5432

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: CivicBook_test
  pool:     5
  username: vagrant
  password: vagrant
  template: template0

production:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: CivicBook_production
  pool:     5
  username: vagrant
  password: vagrant
  template: template0
